apiVersion: v1
kind: ServiceAccount
metadata:
  name: reaper-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reaper.controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reaper-controller
  labels:
    {{- include "reaper.controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["reaper.io"]
    resources: ["reaperpods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["reaper.io"]
    resources: ["reaperpods/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["reaper.io"]
    resources: ["reaperoverlays"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["reaper.io"]
    resources: ["reaperoverlays/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["reaper.io"]
    resources: ["reaperdaemonjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["reaper.io"]
    resources: ["reaperdaemonjobs/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reaper-controller
  labels:
    {{- include "reaper.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reaper-controller
subjects:
  - kind: ServiceAccount
    name: reaper-controller
    namespace: {{ .Release.Namespace }}
