# Secret volume demo — sensitive data mounted as read-only files.
#
# The Secret 'app-credentials' contains username, password, and api-key.
# The pod mounts them at /etc/secrets/ (read-only) and demonstrates
# reading the files and verifying that writes are rejected.
#
# Usage:
#   kubectl apply -f secret-env.yaml
#   kubectl logs secret-reader -f
apiVersion: v1
kind: Pod
metadata:
  name: secret-reader
  labels:
    app: secret-reader
    demo: volumes
spec:
  runtimeClassName: reaper-v2
  nodeSelector:
    role: demo
  restartPolicy: Never
  containers:
    - name: reader
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "=== Secret Volume Demo ==="
          echo "Hostname: $(hostname)"
          echo ""

          echo "--- Listing secret files at /etc/secrets/ ---"
          ls -la /etc/secrets/
          echo ""

          echo "--- Reading secret values (masked) ---"
          for f in /etc/secrets/*; do
            # Skip symlink targets (..data, ..timestamp)
            basename="$(basename "$f")"
            case "$basename" in
              ..*) continue ;;
            esac
            VALUE=$(cat "$f")
            FIRST_CHAR=$(echo "$VALUE" | cut -c1)
            LENGTH=${#VALUE}
            MASKED="${FIRST_CHAR}$(printf '%*s' $((LENGTH - 1)) '' | tr ' ' '*')"
            echo "  $basename = $MASKED  ($LENGTH chars)"
          done
          echo ""

          echo "--- Verifying read-only enforcement ---"
          if (echo "tampered" > /etc/secrets/username) 2>/dev/null; then
            echo "WARNING: Write succeeded (unexpected)"
          else
            echo "Write rejected as expected — secrets are read-only"
          fi
          echo ""

          echo "--- Verifying exact file count ---"
          COUNT=$(ls /etc/secrets/ | grep -v '^\.\.' | wc -l | tr -d ' ')
          echo "Secret files found: $COUNT (expected: 3)"
          echo ""

          echo "=== Secret volume demo complete ==="
      volumeMounts:
        - name: credentials
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: credentials
      secret:
        secretName: app-credentials
