# Install Ansible on all worker nodes via apt.
#
# Runs one pod per worker node (9 pods across 9 workers). Each pod installs
# Ansible into the shared overlay namespace. Since the overlay persists,
# Ansible remains available for subsequent workloads on the same node.
#
# Prerequisites:
#   - Reaper installed on all nodes
#   - Run setup.sh first
#
# Usage:
#   kubectl apply -f install-ansible-job.yaml
#   kubectl wait --for=condition=Complete job/install-ansible --timeout=300s
#   kubectl logs -l job-name=install-ansible --all-containers --prefix
#   kubectl delete job install-ansible
apiVersion: batch/v1
kind: Job
metadata:
  name: install-ansible
  labels:
    app: install-ansible
spec:
  completions: 9
  parallelism: 9
  template:
    metadata:
      labels:
        app: install-ansible
    spec:
      runtimeClassName: reaper-v2
      restartPolicy: Never
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: install-ansible
      containers:
        - name: installer
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "=== Ansible Installation ==="
              echo "Node: $(hostname)"
              echo "Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
              echo ""

              echo "--- Installing Ansible via apt ---"
              apt-get update -qq 2>&1 | tail -1
              apt-get install -y -qq ansible > /dev/null 2>&1
              echo ""

              echo "--- Verifying installation ---"
              ansible --version
              echo ""

              echo "=== Ansible installed successfully on $(hostname) ==="
