#!/usr/bin/env bash
# generate-kind-inventory.sh - Generate Ansible inventory for Kind cluster
#
# This script discovers Kind cluster nodes and generates an Ansible inventory
# that uses Docker connection plugin to access them.
#
# Usage:
#   ./scripts/generate-kind-inventory.sh <cluster-name> [output-file]
#
# If output-file is not specified, prints to stdout.

set -euo pipefail

CLUSTER_NAME="${1:-}"
OUTPUT_FILE="${2:-}"

if [[ -z "$CLUSTER_NAME" ]]; then
  echo "Error: Cluster name required" >&2
  echo "Usage: $0 <cluster-name> [output-file]" >&2
  exit 1
fi

# Check if Kind cluster exists
if ! kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
  echo "Error: Kind cluster '$CLUSTER_NAME' not found" >&2
  echo "Available clusters:" >&2
  kind get clusters 2>/dev/null || echo "  (none)" >&2
  exit 1
fi

# Discover Kind nodes (Docker containers)
NODE_CONTAINERS=$(docker ps --filter "label=io.x-k8s.kind.cluster=${CLUSTER_NAME}" --format '{{.Names}}' | sort)

if [[ -z "$NODE_CONTAINERS" ]]; then
  echo "Error: No nodes found for cluster '$CLUSTER_NAME'" >&2
  exit 1
fi

# Generate inventory content
generate_inventory() {
  cat <<EOF
# Ansible inventory for Kind cluster: ${CLUSTER_NAME}
# Generated by: scripts/generate-kind-inventory.sh
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# This inventory uses Ansible's Docker connection plugin to access
# Kind nodes directly via 'docker exec', which is faster than SSH
# and doesn't require SSH to be installed in the containers.

[k8s_nodes]
EOF

  # Add each node
  for node in $NODE_CONTAINERS; do
    echo "$node ansible_connection=docker ansible_host=$node"
  done

  cat <<EOF

[k8s_nodes:vars]
# Docker connection plugin configuration
ansible_user=root
ansible_become=no
ansible_python_interpreter=/usr/bin/python3

# Docker-specific settings
# Note: Docker connection doesn't use SSH, so these are not needed
# ansible_ssh_private_key_file, ansible_port, etc. are ignored
EOF
}

# Output inventory
if [[ -z "$OUTPUT_FILE" ]]; then
  # Print to stdout
  generate_inventory
else
  # Write to file
  generate_inventory > "$OUTPUT_FILE"
  echo "Inventory written to: $OUTPUT_FILE" >&2
  echo "Nodes discovered:" >&2
  echo "$NODE_CONTAINERS" | sed 's/^/  - /' >&2
fi
