# Run an Ansible playbook to install nginx on login nodes only.
#
# Each pod reads the playbook from the 'nginx-login-playbook' ConfigMap
# and runs it locally with ansible-playbook. Ansible must already be
# installed in the overlay (by the ansible-bootstrap DaemonSet).
#
# Targets only nodes labeled role=login (2 nodes).
#
# Prerequisites:
#   - Reaper installed on all nodes
#   - ansible-bootstrap DaemonSet running (Ansible available in overlay)
#   - ConfigMap 'nginx-login-playbook' created by setup.sh
#   - Nodes labeled role=login
#
# Usage:
#   kubectl apply -f nginx-login-job.yaml
#   kubectl wait --for=condition=Complete job/nginx-login --timeout=300s
#   kubectl logs -l job-name=nginx-login --all-containers --prefix
#   kubectl delete job nginx-login
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-login
  labels:
    app: nginx-login
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: nginx-login
    spec:
      runtimeClassName: reaper-v2
      restartPolicy: Never
      nodeSelector:
        role: login
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: nginx-login
      containers:
        - name: playbook-runner
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "=== Ansible Playbook Runner (login node) ==="
              echo "Node: $(hostname)"
              echo "Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
              echo ""

              echo "--- Checking Ansible is available (installed by bootstrap DaemonSet) ---"
              if ! command -v ansible-playbook >/dev/null 2>&1; then
                echo "ERROR: ansible-playbook not found."
                echo "Deploy the ansible-bootstrap DaemonSet first."
                exit 1
              fi
              ansible --version | head -1
              echo ""

              echo "--- Playbook from ConfigMap ---"
              cat /playbook/playbook.yml
              echo ""

              echo "--- Running playbook ---"
              ansible-playbook /playbook/playbook.yml -v
              RESULT=$?
              echo ""

              if [ $RESULT -eq 0 ]; then
                echo "=== Playbook completed successfully on $(hostname) ==="
              else
                echo "=== Playbook FAILED on $(hostname) (exit code: $RESULT) ==="
                exit $RESULT
              fi
          volumeMounts:
            - name: playbook
              mountPath: /playbook
              readOnly: true
      volumes:
        - name: playbook
          configMap:
            name: nginx-login-playbook
