# Install nginx on login nodes via Ansible playbook — reboot-resilient.
#
# A DaemonSet (not a Job) so kubelet restarts it after a node reboot,
# reinstalling nginx into the fresh overlay. The init container waits
# for Ansible to appear (installed by the ansible-bootstrap DaemonSet),
# so everything can be deployed with a single kubectl apply -f.
#
# Targets only nodes labeled role=login (2 nodes).
#
# Prerequisites:
#   - Reaper installed on all nodes
#   - ConfigMap 'nginx-login-playbook' created by setup.sh
#   - Nodes labeled role=login
#
# Usage:
#   kubectl apply -f examples/07-ansible-complex/
#   kubectl logs -l app=nginx-login --all-containers --prefix
#   kubectl delete daemonset nginx-login
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-login
  labels:
    app: nginx-login
spec:
  selector:
    matchLabels:
      app: nginx-login
  template:
    metadata:
      labels:
        app: nginx-login
    spec:
      runtimeClassName: reaper-v2
      nodeSelector:
        role: login
      initContainers:
        - name: wait-for-ansible
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Ansible in shared overlay (installed by bootstrap DaemonSet)..."
              ATTEMPTS=0
              until command -v ansible-playbook >/dev/null 2>&1; do
                ATTEMPTS=$((ATTEMPTS + 1))
                if [ $ATTEMPTS -ge 150 ]; then
                  echo "ERROR: Timed out after 300s waiting for ansible-playbook"
                  exit 1
                fi
                sleep 2
              done
              echo "Ansible found: $(ansible --version | head -1)"
      containers:
        - name: playbook-runner
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "=== Ansible Playbook Runner (login node) ==="
              echo "Node: $(hostname)"
              echo "Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
              echo ""

              ansible --version | head -1
              echo ""

              echo "--- Running playbook ---"
              ansible-playbook /playbook/playbook.yml -v
              RESULT=$?
              echo ""

              if [ $RESULT -eq 0 ]; then
                echo "=== Playbook completed successfully on $(hostname) — sleeping ==="
              else
                echo "=== Playbook FAILED on $(hostname) (exit code: $RESULT) ==="
                exit $RESULT
              fi

              # Stay alive so kubelet restarts us after reboot
              exec sleep infinity
          volumeMounts:
            - name: playbook
              mountPath: /playbook
              readOnly: true
      volumes:
        - name: playbook
          configMap:
            name: nginx-login-playbook
